# v0.1
name: Theme deployment
on:
  workflow_dispatch:
    inputs:
      blobUrl:
        description: 'Artifact download url'
        required: true
      artifactVersion:
        description: 'Full artifact build number'
        required: true
      key:
        description: 'Deployment config map key'
        required: true
      appDescriptionRepo:
        description: 'ArgoCd repository'
        required: true
        default: 'VirtoCommerce/vc-deploy-apps'
      appDescriptionBranch:
        description: 'ArgoCd branch'
        required: true
        default: 'master'


jobs:
  cd:
    runs-on: ubuntu-latest
    steps:

    - name: Start deployment
      uses: bobheadxi/deployments@master
      id: deployment
      with:
        step: start
        token: ${{ secrets.GITHUB_TOKEN }}
        env: Development
        no_override: false

    - name: Checkout ArgoCD repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
        repository: ${{ github.event.inputs.appDescriptionRepo }}
        ref: ${{ github.event.inputs.appDescriptionBranch }}

    - name: Update deployment-cm
      shell: pwsh
      run: |
        cd ${{ github.workspace }}
        cd ./vst-app/overlays/dev
        $fileName = "./deployment-cm.yaml"
        $content = Get-Content $fileName
        $key = "${{ github.event.inputs.key }}"
        $artifactPath = "${{ github.event.inputs.blobUrl }}"
        $content -replace "$key\s*:.*", "$key`: $artifactPath" | Set-Content -Path $fileName
    - name: Commit deployment-cm change
      shell: pwsh
      run: |
        if(git status --porcelain |Where {$_ -notmatch '^\?\?'}) # uncommitted changes exist
        {
          git config --global user.name 'GitHub Actions'
          git config user.email --global  'github.actions@virtoway.com'
          git commit -am 'Automated update ${{ github.repository }} to ${{ github.event.inputs.artifactVersion }}'
          git push
        }
        else
        {
          Write-Output 'Nothing to commit, working tree clean'
        }
    - name: Wait for environment is up
      shell: pwsh
      timeout-minutes: 5
      run: |
        do {
          Start-Sleep -s 15
          $statusBage = (Invoke-WebRequest -Uri "https://cd.govirto.com/api/badge?name=vst-app-dev").Content

          $syncedAndHealthy = $statusBage.Contains('>Healthy<') -and $statusBage.Contains('>Synced<')
          if (-not $syncedAndHealthy) {
            Write-Host "Sync pending..."
          }
        }
        while (-not $syncedAndHealthy)
    - name: BUILD_STATE::successful
      if: success()
      run: echo "BUILD_STATE=successful" >> $GITHUB_ENV

    - name: BUILD_STATE::failed
      if: failure()
      run: echo "BUILD_STATE=failed"  >> $GITHUB_ENV

    - name: Update GitHub deployment status
      uses: bobheadxi/deployments@master
      if: always()
      with:
        step: finish
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
